version: '3.8'

services:
  # 1. The React Frontend & NGINX API Gateway
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - upload-service
      - auth-service
      - lifecycle-service
      - audit-service

  # 2. Upload Microservice
  upload-service:
    build:
      context: backend
      dockerfile: microservices/upload/Dockerfile
    env_file:
      - .env

  # 3. Auth & Zero Trust Microservice
  auth-service:
    build:
      context: backend
      dockerfile: microservices/auth/Dockerfile
    env_file:
      - .env

  # 4. Lifecycle Microservice
  lifecycle-service:
    build:
      context: backend
      dockerfile: microservices/lifecycle/Dockerfile
    env_file:
      - .env

  # 5. Audit Microservice
  audit-service:
    build:
      context: backend
      dockerfile: microservices/audit/Dockerfile
    env_file:
      - .env
