server {
    listen 80;
    server_name _;
    client_max_body_size 50m;

    # Serve static files for the React SPA
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Simulate AWS ALB API Gateway Routing
    location /api/upload { proxy_pass http://upload-service:80; }
    
    location /api/verify { proxy_pass http://auth-service:80; }
    location /api/access { proxy_pass http://auth-service:80; }
    
    location /api/delete { proxy_pass http://lifecycle-service:80; }
    location /api/expiry { proxy_pass http://lifecycle-service:80; }
    
    location /api/dashboard { proxy_pass http://audit-service:80; }
    location /api/logs { proxy_pass http://audit-service:80; }
    location /api/alerts { proxy_pass http://audit-service:80; }
    location /api/services/status { proxy_pass http://audit-service:80; }


}
