apiVersion: apps/v1
kind: Deployment
metadata:
  name: zerotrust-audit
  labels:
    app: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audit
  template:
    metadata:
      labels:
        app: audit
    spec:
      containers:
      - name: audit
        image: 494003775847.dkr.ecr.eu-north-1.amazonaws.com/zerotrust-audit:latest
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: backend-env
---
apiVersion: v1
kind: Service
metadata:
  name: audit-service
spec:
  type: ClusterIP
  selector:
    app: audit
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
