apiVersion: v1
kind: Service
metadata:
  name: zero-trust-backend-service
  labels:
    app: zero-trust-backend
spec:
  type: ClusterIP
  selector:
    app: zero-trust-backend
  ports:
    - name: http
      port: 8000
      targetPort: 8000
