apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-trust-frontend
  labels:
    app: zero-trust-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero-trust-frontend
  template:
    metadata:
      labels:
        app: zero-trust-frontend
    spec:
      containers:
        - name: frontend
          image: zero-trust-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
