apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zerotrust-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/success-codes: "200-499"
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          # Frontend Route
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80

          # Upload Microservice Routes
          - path: /api/upload
            pathType: Prefix
            backend:
              service:
                name: upload-service
                port:
                  number: 80
                  
          # Auth/Zero Trust Microservice Routes
          - path: /api/verify
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80
          - path: /api/access
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 80

          # Lifecycle Microservice Routes
          - path: /api/delete
            pathType: Prefix
            backend:
              service:
                name: lifecycle-service
                port:
                  number: 80
          - path: /api/expiry
            pathType: Prefix
            backend:
              service:
                name: lifecycle-service
                port:
                  number: 80

          # Audit/Dashboard Microservice Routes
          - path: /api/dashboard
            pathType: Prefix
            backend:
              service:
                name: audit-service
                port:
                  number: 80
          - path: /api/logs
            pathType: Prefix
            backend:
              service:
                name: audit-service
                port:
                  number: 80
          - path: /api/alerts
            pathType: Prefix
            backend:
              service:
                name: audit-service
                port:
                  number: 80
          - path: /api/services/status
            pathType: Prefix
            backend:
              service:
                name: audit-service
                port:
                  number: 80
